config/routes.rb
Quizzer::Application.routes.draw do

  root "quizzes#index"

  get "reshuffle_queue" => "quizzes#reshuffle_queue"

  resources :quizzes do
    get "current_card" => "quizzes#current_card"
    post "next_card" => "quizzes#next_card"
    post "prev_card" => "quizzes#prev_card"
    resources :cards, :only => [:show]
  end

  resources :categories, :except => [:show]
  resources :cards, :except => [:show]
  

  

end

app/models/card.rb
class Card < ActiveRecord::Base

  has_many :card_views
  belongs_to :category

  validates :title, :presence => true
  validates :body, :presence => true
  validates :category, :presence => true

  # update the stats: add a pass and reduce a prior fail if any
  def pass(user)
    cv = CardView.find_or_create(user, self)
    cv.pass_count += 1
    cv.urgency -= 1 if cv.urgency > 0
    cv.save!
  end

  # update the stats: add a fail and upgrade urgency
  def fail(user)    
    cv = CardView.find_or_create(user, self)
    cv.fail_count += 1
    cv.urgency += 1
    cv.save!
  end


end

app/models/card_view.rb
class CardView < ActiveRecord::Base

  belongs_to :user
  belongs_to :card

  def self.find_or_create(user, card)
    cv = CardView.where(:user => user, :card => card).first
    if cv.nil?
      cv = CardView.create!(:user => user, :card => card)
    end
    cv
  end

  # returns the decimal representing the % of how close to the front
  # of the queue the card should be reshuffled into, e.g.
  # .3 means it should be placed in the nearest 30%
  def get_shuffle_location
    pass_rate = (1.0 * self.pass_count / ( self.pass_count + self.fail_count ))
    shuffle_location = [2 * (pass_rate / (1.0+ 3 * self.urgency) ), 1].min
    puts "\n\nSHUFFLE pct is : #{shuffle_location}\n\n"
    shuffle_location
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  # cards will always be shown as part of a quiz (okay, for now)
  def show
    @quiz = Quiz.find(params[:quiz_id])
    @card = Card.find(params[:id])
    @user = @quiz.user
    cv = @card.card_views.where(:user => @user)
    if cv.empty?
      @card_views = nil
    else
      @card_views = cv.first
    end
  end


  def index
    @cards = Card.all
    @categories = Category.includes(:cards)
  end

  def new
    @card = Card.new
    unless cookies[:category_id].nil?
      @card.category_id = cookies[:category_id] 
    end
  end

  def create
    @card = Card.new(card_params)
    cookies[:category_id] = card_params[:category_id]
    if @card.save
      flash[:success] = "Card #{@card.title} created!"
      redirect_to new_card_path
    else
      flash.now[:error] = "Couldn't create card because: #{@card.errors.full_messages}"
      render :new
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      flash[:success] = "Card #{@card.title} updated!"
      redirect_to cards_path
    else
      flash.now[:error] = "Couldn't update card because: #{@card.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    if @card.destroy
      flash[:success] = "Destroyed card #{@card.title}!"
      redirect_to cards_path
    else
      flash.now[:error] = "Couldn't delete card for some reason, check logs.  Errors: #{@card.errors.full_messages}."
      render :edit
    end
  end


  private

  def card_params
    params.require(:card).permit(:title, :body, :category_id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card_form.html.erb
<div class="new-something">
  <%= simple_form_for card do |f| %>

    <div class="input">
      <%= f.input :title %>
    </div>
    <div class="input">
      <%= f.input :body %>
    </div>
    <div class="input">
      <%= f.association :category %>
    </div>
    <div class="input">
      <%= f.submit %>
    </div>

  <% end %>
  <% if card.persisted? %>
    <%= link_to "Delete card", card, :method => :delete, :confirm => "Are you SURE you want to delete this?" %>
  <% end %>
</div>

app/views/cards/_card_stats.html.erb
<div class="card-stats">
  <ul>
    <% if @card_views %>
      <li>
        <%= @card_views.pass_count %> Pass 
      </li>
      <li>
        <%= @card_views.fail_count %> Fail
      </li>
      <li>
        ==> <%= ((@card_views.pass_count / (@card_views.pass_count + @card_views.fail_count).to_f).to_f * 100).round(1) %>%
      </li>
      <!-- <li>
        <%= @card_views.pass_count + @card_views.fail_count %> Views
      </li> -->
      <hr>
      <li>
        <%= @card_views.urgency %> Urgency
      </li>
    <% else %>
      <li>
        This card is brand new!
      </li>
    <% end %>
  </ul>
</div>

app/views/cards/_pass_fail.html.erb
<div class="pass-fail-buttons">

  <%= button_to "X", quiz_next_card_path(quiz, :card_status => "fail", :card_id => card_id), :method => :post, :class => "fail-button decision-button" %>

  <%= button_to "&#10003;".html_safe, quiz_next_card_path(quiz, :card_status => "pass", :card_id => card_id), :method => :post, :class => "pass-button decision-button" %>

</div>

app/views/cards/_sidebar.html.erb
<h4>Action Buttons</h4>
<ul>
  <li><%= link_to "Reshuffle queue", reshuffle_queue_path(:quiz_id=>quiz.id) %></li>
  <li><%= link_to "Edit Card", edit_card_path(card.id), :target => "blank" %></li>
</ul>

<h4>Possible Upcoming Cards:</h4>

<ol>
  <% quiz.queue.each do |cid| %>
    <li><%= Card.find(cid).title %></li>
  <% end %>
</ol>

app/views/cards/edit.html.erb
<h1>Edit Card <%= @card.title %></h1>

<%= render :partial => "card_form", :locals => { :card => @card } %>

app/views/cards/index.html.erb
<h1>Cards</h1>

<%= link_to new_card_path do%>
  <div class="new-something-link">
    New Card
  </div>
<% end %>

<div id="list">

  <ul>
    <% @categories.each do |cat| %>
      <li><%= link_to cat.name, edit_category_path(cat), :class => "category" %>
        <ol>
          <% cat.cards.each do |card| %>
            <%= link_to edit_card_path(card) do %>
              <li><%= card.title %></li>
            <% end %>
          <% end %>
        </ol>
      </li>
    <% end %>
  </ul>

</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render :partial => "card_form", :locals => {:card => @card} %>

app/views/cards/show.html.erb
<div id="show-card">

  <div class="title">
    <h1><%= @quiz.name %></h1>
  </div>

  <div class="card-category">
    <h2>Category: <%= @card.category.name %></h2>
  </div>

  <div class="top-action-pack">
    <%= render :partial => "pass_fail", :locals => { :quiz => @quiz, :card_id => @card.id } %>
    <%= render :partial => "card_stats", :locals => { :card_views => @card_views } %>
  </div>

  <div class="card-title">
    <h1>Q: <%= @card.title %></h1>
  </div>

  <button class="show-button" onClick="Card.showBody()">
    Show Answer
  </button>
  <div class="card-body">
    <%= md(@card.body).html_safe %>
  </div>


  <div class="bottom-action-pack">
    <%= render :partial => "pass_fail", :locals => { :quiz => @quiz, :card_id => @card.id } %>
  </div>
  
  <div class="sidebar-stats">
    <%= render :partial => "sidebar", :locals => { :quiz => @quiz, :card => @card } %>
  </div>
</div>