config/routes.rb
Quizzer::Application.routes.draw do

  root "quizzes#index"

  get "reshuffle_queue" => "quizzes#reshuffle_queue"

  resources :quizzes do
    get "current_card" => "quizzes#current_card"
    post "next_card" => "quizzes#next_card"
    post "prev_card" => "quizzes#prev_card"
    resources :cards, :only => [:show]
  end

  resources :categories, :except => [:show]
  resources :cards, :except => [:show]
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :cards, :dependent => :destroy
  has_many :quiz_categories, :dependent => :destroy

  validates :name, :presence => true

  def new_queue
    self.cards.shuffle.map(&:id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category #{@category.name} created!"
      redirect_to categories_path
    else
      flash.now[:error] = "Couldn't create category because: #{@category.errors.full_messages}"
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category #{@category.name} updated!"
      redirect_to categories_path
    else
      flash.now[:error] = "Couldn't update category because: #{@category.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = "Destroyed category #{@category.name}!"
      redirect_to categories_path
    else
      flash.now[:error] = "Couldn't delete category for some reason, check logs.  Errors: #{@category.errors.full_messages}."
      render :edit
    end
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_form.html.erb
<%= simple_form_for category do |f| %>

  <%= f.input :name %>
  <%= f.submit %>

<% end %>
<% if category.persisted? %>
  <%= link_to "Delete Category", category, :method => :delete, :confirm => "Are you SURE you want to delete this?  It will remove all cards in this category!!!" %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category <%= @category.name %></h1>

<%= render :partial => "category_form", :locals => { :category => @category } %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div class="new-something-link">
  <%= link_to "New Category", new_category_path %>
</div>

<div id="categories-list">

  <ul>
    <% @categories.each do |cat| %>
      <%= link_to edit_category_path(cat) do %>
        <li><%= cat.name %></li>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<div class="new-something">
  <%= render :partial => "category_form", :locals => {:category => @category} %>
</div>